---
- name: Crear o actualizar usuarios AD via túnel SSH y enviar credenciales por correo
  hosts: "{{ domain_server }}"
  gather_facts: no
  serial: 1

  vars:
    puerto_base_tunel_local: 59850
    usuarios:
      - user: kyndpmoran
        description: "815/K/000636/Kyndryl/Peter Principe/"
        name: Peter
        lastname: Moran
        mail: Peter.MORAN.PRINCIPE@kyndryl.com
      - user: kyndaaroni
        description: "815/K/001616/Kyndryl/Anthony Aroni Quispe/"
        name: Anthony
        lastname: Aroni
        mail: Anthony.Aroni.Quispe1@kyndryl.com
      - user: kyndiarbulu
        description: "815/K/001710/Kyndryl/Ionatan Ballesteros/"
        name: Ionatan
        lastname: Arbulu
        mail: Ionatan.Arbulu1@kyndryl.com
      - user: kyndoalvarez
        description: "815/K/001777/Kyndryl/Oscar Garcia/"
        name: Oscar
        lastname: Alvarez
        mail: Oscar.Alvarez.Garcia@kyndryl.com
      - user: kyndjfranco
        description: "815/K/6025943/Kyndryl/Jesus Augusto Franco/"
        name: Jesus
        lastname: Franco
        mail: jesusaugusto.franco@kyndryl.com
      - user: kyndjlegua
        description: "815/K/001785/Kyndryl/Juan Cano/"
        name: Juan Jose
        lastname: Legua
        mail: Juan.Legua.Cano1@kyndryl.com
      - user: kyndegil
        description: "815/K/001337/Kyndryl/Eder Jean Gil Chacon/"
        name: Eder
        lastname: Gil
        mail: Eder.Gil.Chacon@kyndryl.com
      - user: kyndrmontoya
        description: "815/K/002294/Kyndryl/Ronald Montoya/"
        name: Ronald
        lastname: Montoya
        mail: ronaldenrique.montoya@kyndryl.com
      - user: kyndrsanchez
        description: "815/K/6042664/Kyndryl/Roberto Sanchez/"
        name: Roberto
        lastname: Sanchez
        mail: robertoalexander.sanchez@kyndryl.com
      - user: kyndmartin
        description: "815/K/000944/Kyndryl/Aparicio Torres Martin Josimar/"
        name: Martin
        lastname: Aparicio
        mail: maparicio@kyndryl.com
      - user: kyndicortez
        description: "851/K/6042666/Kyndryl/Ivan Cortez/"
        name: Ivan
        lastname: Cortez
        mail: ivanwalter.cortezana@kyndryl.com
      - user: kyndaluna
        description: "815/K/000839/Kyndryl/Alvaro Edgard Luna Mori/"
        name: Alvaro
        lastname: Luna
        mail: Alvaro.Edgard.Luna.Mori@kyndryl.com
      - user: kyndcvaldivia
        description: "815/K/002268/Kyndryl/Carlos Valdivia Arrunategui/"
        name: Carlos
        lastname: Valdivia
        mail: Carlos.Valdivia.Arrunategui@kyndryl.com
      - user: kyndavaldivia
        description: "815/K/001378/Kyndryl/Arturo Valdivia/"
        name: Arturo
        lastname: Valdivia
        mail: Arturo.Valdivia@kyndryl.com
      - user: kyndjlanda
        description: "815/K/6027104/Kyndryl/Jose Landa/"
        name: Jose
        lastname: Landa
        mail: jose.landa@kyndryl.com
      - user: kyndjbustios
        description: "815/K/001818/Kyndryl/Jose Bustios/"
        name: Jose
        lastname: Bustios
        mail: Jose.Bustios@kyndryl.com

  pre_tasks:
    - name: Calcular puerto dinámico de túnel
      set_fact:
        puerto_dinamico_tunel: "{{ puerto_base_tunel_local | int + ansible_play_hosts_all.index(inventory_hostname) | int }}"

    - name: Establecer ansible_port
      set_fact:
        ansible_port: "{{ puerto_dinamico_tunel }}"

    - name: Establecer túnel SSH
      command: >
        ssh -f -N -L {{ puerto_dinamico_tunel }}:{{ target_actual_ip }}:{{ target_actual_winrm_port }}
        -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ExitOnForwardFailure=yes
        -o ServerAliveInterval=60 -o ConnectTimeout=15
        {{ jumphost_user }}@{{ jumphost_ip }}
      delegate_to: localhost
      changed_when: false
      register: tunnel_setup_status

    - name: Esperar que el túnel esté activo
      wait_for:
        host: 127.0.0.1
        port: "{{ puerto_dinamico_tunel }}"
        timeout: 20
        delay: 2
        state: started
      delegate_to: localhost
      when: tunnel_setup_status.rc == 0

  tasks:
    - name: Crear o actualizar usuarios y enviar correo con credenciales
      win_shell: |
        $usuarios = ConvertFrom-Json @'
        {{ usuarios | to_json }}
        '@
        $domain = (Get-ADDomain).NetBIOSName

        foreach ($u in $usuarios) {
          $username = $u.user
          $password = -join ((65..90)+(97..122)+(48..57) | Get-Random -Count 15 | ForEach-Object {[char]$_})
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (Get-ADUser -Filter "SamAccountName -eq '$username'") {
              Set-ADUser -Identity $username -DisplayName "$($u.name) $($u.lastname)" `
                -Description $u.description -EmailAddress $u.mail `
                -GivenName $u.name -Surname $u.lastname
              Set-ADAccountPassword -Identity $username -NewPassword $securePass -Reset
          } else {
              New-ADUser -Name "$($u.name) $($u.lastname)" -SamAccountName $username `
                -UserPrincipalName "$username@$domain.net" `
                -DisplayName "$($u.name) $($u.lastname)" `
                -GivenName $u.name -Surname $u.lastname `
                -Description $u.description -EmailAddress $u.mail `
                -AccountPassword $securePass -Enabled $true
          }

          $body = "Hola`n`n$($u.name) $($u.lastname), la contraseña de su usuario $username es $password del dominio $domain`n`nSaludos Cordiales"
          Send-MailMessage -To $u.mail -From 'Ansible Automation <ansible@gromero.net>' `
            -Subject "Credenciales de acceso al dominio $domain" `
            -Body $body -SmtpServer "10.32.2.113" -Port 25
        }
      register: resultado_usuarios

    - name: Mostrar resultado
      debug:
        var: resultado_usuarios.stdout_lines

  post_tasks:
    - name: Cerrar túnel SSH
      delegate_to: localhost
      command: >
        pkill -f "ssh .* -L {{ puerto_dinamico_tunel}}:{{ target_actual_ip }}:{{ target_actual_winrm_port }}.*{{ jumphost_user }}@{{ jumphost_ip }}"
      changed_when: false
      failed_when: false
