- name: Ejecutar script IAM según disponibilidad de Perl
  hosts: all
  become: false
  tasks:

    - name: Verificar si Perl está instalado
      command: which perl
      register: perl_check
      failed_when: false
      changed_when: false

    - name: Copiar script Perl si Perl está disponible
      copy:
        src: iam_extract_global.pl
        dest: /tmp/iam_extract_global.pl
        mode: '0755'
      when: perl_check.rc == 0

    - name: Ejecutar script Perl con sudo
      become: true
      command: perl /tmp/iam_extract_global.pl
      register: salida_script_perl
      failed_when: salida_script_perl.rc != 0 and salida_script_perl.rc != 8
      when: perl_check.rc == 0

    - name: Copiar script Shell si Perl NO está disponible
      copy:
        src: iam_extract_global.sh
        dest: /tmp/iam_extract_global.sh
        mode: '0755'
      when: perl_check.rc != 0

    - name: Ejecutar script Shell con sudo
      become: true
      command: /bin/bash /tmp/iam_extract_global.sh
      register: salida_script_sh
      failed_when: salida_script_sh.rc != 0 and salida_script_sh.rc != 8
      when: perl_check.rc != 0

    - name: Mostrar salida del script Perl (si se ejecutó)
      debug:
        var: salida_script_perl.stdout_lines
      when: perl_check.rc == 0

    - name: Mostrar salida del script Shell (si se ejecutó)
      debug:
        var: salida_script_sh.stdout_lines
      when: perl_check.rc != 0
